name: CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job de Deploy no Docker Hub
  deploy-docker:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD_FLASK_WEB }}

      # 3. Build da imagem Docker
      - name: Build Docker image
        run: |
          docker build -t wisomar/Projeto-flask-web:${{ github.sha }} .

      # 4. Push da imagem Docker
      - name: Push Docker image
        run: |
          docker push wisomar/Projeto-flask-web:${{ github.sha }}

  # Job de Deploy no Vercel
  deploy-vercel:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instalar Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel

      # 3. Fazer deploy para o Vercel
      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.PROJETO_FLASK_WEB }} --yes
